version: '3.8'

services:
  db:
    image: postgres:13
    container_name: coinjournal
    restart: always
    environment:
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coinjournal
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
